### ISSUE TITLE
Importing folders of AT files giving unexpected error

### ISSUE THREAD

**Issue by elisagb** [myter/IntelliJAT#8]
![screen shot 2016-11-04 at 11 53 25](https://cloud.githubusercontent.com/assets/2499800/20003317/1eecb74a-a286-11e6-99c0-7f7fa2e1cc31.png)
No clue why this error happens when I try to add an AT folder to the project

**Comment by myter** [comment]
That's not a bug, that's because you used "import settings" to import a folder. Import folders by copy pasting them.
